paths-ignore:
  - "src/workerd/api/node/crypto_keys-test.js"
  - "src/workerd/api/node/crypto_dh-test.js"
  - "src/workerd/jsg/url-test-corpus-success.h"
  - "src/workerd/api/node/tests/crypto_x509-test.js"
